/**
 * Official Reference Dataset for Indian States, Union Territories, and Districts
 * Used for standardized healthcare administrative directory and partner registration.
 */

export interface StateLocation {
  code: string;
  name: string;
  districts: string[];
}

export const INDIAN_STATES_AND_DISTRICTS: StateLocation[] = [
  {
    code: 'WB',
    name: 'West Bengal',
    districts: [
      'Kolkata',
      'North 24 Parganas',
      'South 24 Parganas',
      'Howrah',
      'Hooghly',
      'Nadia',
      'Murshidabad',
      'Purba Medinipur',
      'Paschim Medinipur',
      'Jhargram',
      'Purulia',
      'Bankura',
      'Purba Bardhaman',
      'Paschim Bardhaman',
      'Birbhum',
      'Malda',
      'Uttar Dinajpur',
      'Dakshin Dinajpur',
      'Darjeeling',
      'Kalimpong',
      'Jalpaiguri',
      'Alipurduar',
      'Cooch Behar',
    ],
  },
  {
    code: 'MH',
    name: 'Maharashtra',
    districts: [
      'Mumbai City',
      'Mumbai Suburban',
      'Thane',
      'Palghar',
      'Raigad',
      'Pune',
      'Nagpur',
      'Nashik',
      'Aurangabad',
      'Solapur',
      'Amravati',
      'Kolhapur',
      'Satara',
      'Sangli',
      'Ahmednagar',
      'Jalgaon',
      'Nanded',
      'Akola',
      'Latur',
      'Dhule',
      'Chandrapur',
      'Parbhani',
      'Jalna',
      'Buldhana',
      'Beed',
      'Yavatmal',
      'Osmanabad',
      'Nandurbar',
      'Wardha',
      'Washim',
      'Hingoli',
      'Gadchiroli',
      'Bhandara',
      'Gondia',
      'Sindhudurg',
      'Ratnagiri',
    ],
  },
  {
    code: 'DL',
    name: 'Delhi',
    districts: [
      'Central Delhi',
      'East Delhi',
      'New Delhi',
      'North Delhi',
      'North East Delhi',
      'North West Delhi',
      'Shahdara',
      'South Delhi',
      'South East Delhi',
      'South West Delhi',
      'West Delhi',
    ],
  },
  {
    code: 'KA',
    name: 'Karnataka',
    districts: [
      'Bengaluru Urban',
      'Bengaluru Rural',
      'Mysuru',
      'Belagavi',
      'Ballari',
      'Bidar',
      'Vijayapura',
      'Chamarajanagar',
      'Chikkaballapura',
      'Chikkamagaluru',
      'Chitradurga',
      'Dakshina Kannada',
      'Davanagere',
      'Dharwad',
      'Gadag',
      'Hassan',
      'Haveri',
      'Kalaburagi',
      'Kodagu',
      'Kolar',
      'Koppal',
      'Mandya',
      'Raichur',
      'Ramanagara',
      'Shivamogga',
      'Tumakuru',
      'Udupi',
      'Uttara Kannada',
      'Yadgir',
    ],
  },
  {
    code: 'TN',
    name: 'Tamil Nadu',
    districts: [
      'Chennai',
      'Coimbatore',
      'Madurai',
      'Tiruchirappalli',
      'Salem',
      'Tirunelveli',
      'Tiruppur',
      'Vellore',
      'Erode',
      'Thoothukudi',
      'Dindigul',
      'Thanjavur',
      'Ranipet',
      'Virudhunagar',
      'Karur',
      'Nilgiris',
      'Kanchipuram',
      'Chengalpattu',
      'Tiruvallur',
      'Cuddalore',
      'Nagapattinam',
      'Kanyakumari',
    ],
  },
  {
    code: 'UP',
    name: 'Uttar Pradesh',
    districts: [
      'Lucknow',
      'Kanpur Nagar',
      'Varanasi',
      'Agra',
      'Prayagraj',
      'Ghaziabad',
      'Gautam Buddha Nagar (Noida)',
      'Meerut',
      'Bareilly',
      'Aligarh',
      'Moradabad',
      'Saharanpur',
      'Gorakhpur',
      'Ayodhya',
      'Jhansi',
      'Mathura',
      'Muzaffarnagar',
    ],
  },
  {
    code: 'GJ',
    name: 'Gujarat',
    districts: [
      'Ahmedabad',
      'Surat',
      'Vadodara',
      'Rajkot',
      'Bhavnagar',
      'Jamnagar',
      'Junagadh',
      'Gandhinagar',
      'Anand',
      'Navsari',
      'Morbi',
      'Bharuch',
      'Porbandar',
      'Kutch',
      'Mehsana',
    ],
  },
  {
    code: 'BR',
    name: 'Bihar',
    districts: [
      'Patna',
      'Gaya',
      'Bhagalpur',
      'Muzaffarpur',
      'Purnia',
      'Darbhanga',
      'Bihar Sharif',
      'Arrah',
      'Begusarai',
      'Katihar',
      'Munger',
      'Chhapra',
      'Saharsa',
      'Sasaram',
      'Hajipur',
      'Dehri',
      'Siwan',
      'Motihari',
      'Nawada',
      'Bagaha',
    ],
  },
  {
    code: 'KL',
    name: 'Kerala',
    districts: [
      'Thiruvananthapuram',
      'Kollam',
      'Pathanamthitta',
      'Alappuzha',
      'Kottayam',
      'Idukki',
      'Ernakulam (Kochi)',
      'Thrissur',
      'Palakkad',
      'Malappuram',
      'Kozhikode',
      'Wayanad',
      'Kannur',
      'Kasaragod',
    ],
  },
  {
    code: 'RJ',
    name: 'Rajasthan',
    districts: [
      'Jaipur',
      'Jodhpur',
      'Kota',
      'Bikaner',
      'Ajmer',
      'Udaipur',
      'Bhilwara',
      'Alwar',
      'Bharatpur',
      'Sikar',
      'Pali',
      'Sri Ganganagar',
      'Tonk',
      'Kishangarh',
      'Beawar',
      'Hanumangarh',
    ],
  },
  {
    code: 'TG',
    name: 'Telangana',
    districts: [
      'Hyderabad',
      'Medchal-Malkajgiri',
      'Rangareddy',
      'Warangal Urban',
      'Nizamabad',
      'Khammam',
      'Karimnagar',
      'Ramagundam',
      'Mahabubnagar',
      'Nalgonda',
      'Adilabad',
      'Suryapet',
      'Miryalaguda',
      'Siddipet',
    ],
  },
  {
    code: 'AP',
    name: 'Andhra Pradesh',
    districts: [
      'Visakhapatnam',
      'Vijayawada (NTR)',
      'Guntur',
      'Nellore',
      'Kurnool',
      'Kakinada',
      'Rajahmundry (East Godavari)',
      'Kadapa',
      'Tirupati',
      'Anantapur',
      'Vizianagaram',
      'Eluru',
      'Ongole (Prakasam)',
      'Srikakulam',
      'Machilipatnam (Krishna)',
    ],
  },
  {
    code: 'OD',
    name: 'Odisha',
    districts: [
      'Bhubaneswar (Khurda)',
      'Cuttack',
      'Rourkela (Sundargarh)',
      'Berhampur (Ganjam)',
      'Sambalpur',
      'Puri',
      'Balasore',
      'Bhadrak',
      'Baripada (Mayurbhanj)',
      'Jharsuguda',
      'Angul',
      'Dhenkanal',
    ],
  },
  {
    code: 'JH',
    name: 'Jharkhand',
    districts: [
      'Ranchi',
      'Jamshedpur (East Singhbhum)',
      'Dhanbad',
      'Bokaro',
      'Deoghar',
      'Hazaribagh',
      'Giridih',
      'Ramgarh',
      'Medininagar (Palamu)',
      'Chaibasa (West Singhbhum)',
    ],
  },
  {
    code: 'AS',
    name: 'Assam',
    districts: [
      'Guwahati (Kamrup Metropolitan)',
      'Kamrup Rural',
      'Dibrugarh',
      'Silchar (Cachar)',
      'Jorhat',
      'Nagaon',
      'Tinsukia',
      'Tezpur (Sonitpur)',
      'Bongaigaon',
      'Barpeta',
    ],
  },
];

export function getAllStates(): { code: string; name: string }[] {
  return INDIAN_STATES_AND_DISTRICTS.map((s) => ({
    code: s.code,
    name: s.name,
  }));
}

export function getDistrictsByState(stateNameOrCode: string): string[] {
  if (!stateNameOrCode) return [];
  const clean = stateNameOrCode.trim().toLowerCase();
  const match = INDIAN_STATES_AND_DISTRICTS.find(
    (s) => s.code.toLowerCase() === clean || s.name.toLowerCase() === clean
  );
  return match ? [...match.districts].sort() : [];
}

export function isValidState(stateNameOrCode: string): boolean {
  if (!stateNameOrCode) return false;
  const clean = stateNameOrCode.trim().toLowerCase();
  return INDIAN_STATES_AND_DISTRICTS.some(
    (s) => s.code.toLowerCase() === clean || s.name.toLowerCase() === clean
  );
}

export function isValidDistrictForState(stateNameOrCode: string, districtName: string): boolean {
  if (!stateNameOrCode || !districtName) return false;
  const districts = getDistrictsByState(stateNameOrCode);
  const cleanDistrict = districtName.trim().toLowerCase();
  return districts.some((d) => d.toLowerCase() === cleanDistrict);
}
